DesafioFluxoCaixa/Controllers/CRUDController.cs
using DesafioFluxoCaixa.Models;
using Microsoft.AspNetCore.Mvc;
using DesafioFluxoCaixa.CRUD;
using System;
using DesafioFluxoCaixa.Models.Pessoas;
using System.Threading.Tasks;
using DesafioFluxoCaixa.Models.Contas;
using DesafioFluxoCaixa.Models.Transacoes;
using System.Text.Json;
using Microsoft.AspNetCore.Http;
using ISession = NHibernate.ISession;
using System.Reflection;
using DesafioFluxoCaixa.Models.Excecoes;

namespace DesafioFluxoCaixa.Controllers
{
    public class CRUDController : Controller
    {
        private readonly Microsoft.AspNetCore.Http.IHttpContextAccessor _contxt;
        private readonly ISession _session;
        private readonly PersonRep PersonCRUD;
        private readonly WithdrawRep WithdrawCRUD;
        private readonly DepositRep DepositCRUD;
        private readonly AccountRep AccountCRUD;
        private ServicoEmail servicoEmail;

        public CRUDController(ISession session, Microsoft.AspNetCore.Http.IHttpContextAccessor httpContextAccessor, ServicoEmail _servicoEmail)
        {
            _session = session;
            _contxt = httpContextAccessor;
            PersonCRUD = new PersonRep(_session);
            AccountCRUD = new AccountRep(_session);
            DepositCRUD = new DepositRep(_session);
            WithdrawCRUD = new WithdrawRep(_session);
            servicoEmail = _servicoEmail;
        }

        public IActionResult Cadastro()
        {
            return View();
        }

        public async Task<JsonResult> AlterarConta(int id)
        {
            Account account = await AccountCRUD.FindByID(id);
            return Json(account);
        }

        public async Task<JsonResult> DeletarDados(int id)
        {
            await PersonCRUD.Remove(id);

            return Json(true);
        }

        public IActionResult SelecionarConta()
        {
            return View(AccountCRUD.FindAll());
        }

        public IActionResult SelecionarContaDeposito()
        {
            return View(AccountCRUD.FindAll());
        }

        public IActionResult SelecionarContaSaque()
        {
            return View(AccountCRUD.FindAll());
        }

        [HttpPost]
        public async Task<JsonResult> AtualizarConta(Account conta)
        {
            Account Conta = new(conta.MinimalBalance, conta.Limit);

            var account = await AccountCRUD.FindByID(conta.Id);

            account.Limit = Conta.Limit;
            account.MinimalBalance = Conta.MinimalBalance;

            await AccountCRUD.Update(account);

            return Json(account);
        }

        [HttpPost]
        public async Task<JsonResult> Sacar(DadosTransacao DadosSaque)
        {
            Person person = JsonSerializer.Deserialize<Person>(HttpContext.Session.GetString("User"));
            var conta = await AccountCRUD.FindByID(Convert.ToInt32(DadosSaque.ContaId));
            person.Conta = conta;

            Withdraw saque = new(conta, Convert.ToDouble(DadosSaque.Valor.Replace('.',',')), DadosSaque.Descricao, DateTime.Now);

            await WithdrawCRUD.Add(saque);
            await AccountCRUD.Update(conta);

            string msg = null;
            if (conta.IsUnderMinimal())
            {
                msg = "Cuidado! Sua conta está abaixo do mínimo cadastrado.";
                servicoEmail.EnviarEmail(new[] { person.Email },
                    "Saldo abaixo do mínimo!",
                     person.Name,
                    $"Cuidado. Sua conta em Desafio Fluxo de Caixa está com o saldo em R${conta.MinimalBalance - conta.Balance} abaixo do mínimo cadastrado.");
            }

            JsonpResult Retorno = new(person, msg);
            return Json(Retorno);
        }

        [HttpPost]
        public async Task<JsonResult> Depositar(DadosTransacao deposit)
        {
            Person person = JsonSerializer.Deserialize<Person>(HttpContext.Session.GetString("User"));

            var conta = await AccountCRUD.FindByID(Convert.ToInt32(deposit.ContaId));
            Deposit deposit_atualizado = new(conta, Convert.ToDouble(deposit.Valor.Replace('.',',')), deposit.Descricao, DateTime.Now);
            await DepositCRUD.Add(deposit_atualizado);
            await AccountCRUD.Update(conta);

            return Json(person);
        }

        [HttpGet]
        public async Task<JsonResult> AlterarPessoa(int id)
        {
            Person person = await PersonCRUD.FindByID(id);

            return Json(person);
        }

        // POST: Persons/Edit
        [HttpPost]
        public async Task<JsonResult> AtualizarPessoa(Person person)
        {
            Person pessoa = new(person.Id, person.Name, person.Email, person.Password, person.Salario);
            await PersonCRUD.Update(pessoa);

            return Json(person);
        }

        public IActionResult SelecionarPessoa()
        {
            return View(PersonCRUD.FindAll());
        }

        // POST: Persons/Create
        [HttpPost]
        public async Task<JsonResult> SendCadastro(Cadastro data)
        {
            Person person = new Person
                (
                    data.Nome, data.Email,
                    data.Senha, Convert.ToDouble(data.Salario),
                    new Account(Convert.ToDouble(data.SaldoMinimo))
                );

            person.Conta.Person = person;
            await PersonCRUD.Add(person);
            await AccountCRUD.Add(person.Conta);

            person.Conta = null;
            string jsonString = JsonSerializer.Serialize(person);
            _contxt.HttpContext.Session.SetString("User", jsonString);

            return Json(1);
        }
    }
}

DesafioFluxoCaixa/Controllers/ReportsController.cs
using DesafioFluxoCaixa.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using NHibernate;
using DesafioFluxoCaixa.CRUD;
using System;
using System.Collections;
using System.Linq;
using System.Threading.Tasks;
using DesafioFluxoCaixa.Models.Transacoes;
using System.Text.Json;
using DesafioFluxoCaixa.Models.Pessoas;
using Microsoft.AspNetCore.Http;
using ISession = NHibernate.ISession;
using System.Collections.Generic;

namespace DesafioFluxoCaixa.Controllers
{
    public class ReportsController:Controller
    {
        private readonly Microsoft.AspNetCore.Http.IHttpContextAccessor _contxt;
        private readonly ISession _session;
        private readonly PersonRep PersonCRUD;
        private readonly WithdrawRep WithdrawCRUD;
        private readonly DepositRep DepositCRUD;
        private readonly AccountRep AccountCRUD;

        public ReportsController(ISession session, Microsoft.AspNetCore.Http.IHttpContextAccessor httpContextAccessor)
        {
            _contxt = httpContextAccessor;
            _session = session;
            PersonCRUD = new PersonRep(_session);
            WithdrawCRUD = new WithdrawRep(_session);
            DepositCRUD = new DepositRep(_session);
            AccountCRUD = new AccountRep(_session);
        }

        public IActionResult SelecionarContaReport()
        {
            return View(AccountCRUD.FindAll());
        }
        public IActionResult MostrarPorId(int id)
        {
            IEnumerable deposits = DepositCRUD.FindAllByAccount(id);
            IEnumerable withdraws = WithdrawCRUD.FindAllByAccount(id);

            return View("Transacoes", new TransacoesReport(new FiltroPesquisaTransacoes(), deposits, withdraws));
        }

        public IActionResult Mostrar7Dias(int id)
        {
            IEnumerable deposits = DepositCRUD.FindAllLast7Days(id);
            IEnumerable withdraws = WithdrawCRUD.FindAllLast7Days(id);

            return View("Transacoes", new TransacoesReport(new FiltroPesquisaTransacoes(), deposits, withdraws));
        }

        public IActionResult Mostrar15Dias(int id)
        {
            IEnumerable deposits = DepositCRUD.FindAllLast15Days(id);
            IEnumerable withdraws = WithdrawCRUD.FindAllLast15Days(id);

            return View("Transacoes", new TransacoesReport(new FiltroPesquisaTransacoes(), deposits, withdraws));
        }

        public IActionResult Mostrar30Dias(int id)
        {
            IEnumerable deposits = DepositCRUD.FindAllLast30Days(id);
            IEnumerable withdraws = WithdrawCRUD.FindAllLast30Days(id);

            return View("Transacoes", new TransacoesReport(new FiltroPesquisaTransacoes(), deposits, withdraws));
        }

        [HttpPost]
        public IActionResult FiltrarPeriodo(TransacoesReport viewModel)
        {
            var User = JsonSerializer.Deserialize<Person>(_contxt.HttpContext.Session.GetString("User"));
            viewModel.FiltroPesquisaTransacoes.UserId = User.Id;

            viewModel.Deposits = DepositCRUD.FindAllByDates(viewModel.FiltroPesquisaTransacoes);
            viewModel.Withdraws = WithdrawCRUD.FindAllByDates(viewModel.FiltroPesquisaTransacoes);

            return View("Transacoes", viewModel);
        }

        public IActionResult Pessoas()
        {
            return View(PersonCRUD.FindAll());
        }

        public IActionResult Contas()
        {
            return View(AccountCRUD.FindAll());
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DesafioFluxoCaixa/Views/Shared/_Layout.cshtml
@using System.Text.Json
@using Microsoft.AspNetCore.Http
@using DesafioFluxoCaixa.Models.Pessoas
@inject IHttpContextAccessor HttpContextAccessor

@{
    var User = JsonSerializer.Deserialize<Person>(HttpContextAccessor.HttpContext.Session.GetString("User"));
}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] - DesafioFluxoCaixa</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Custom styles for this template -->
    <link href="~/css/sidebars.css" rel="stylesheet">
    <link href="~/css/site.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous" asp-append-version="true"></script>
    <script src="~/js/site.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.1/dist/sweetalert2.all.min.js"></script>
    <script src="~/lib/knockout-3.5.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout-validation/2.0.4/knockout.validation.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://unpkg.com/imask"></script>

</head>
<body>
    <main role="main">
        <aside class="flex-shrink-0 p-3 bg-white">
            <a asp-controller="Home" asp-action="Index" class="d-flex align-items-start pb-3 mb-3 link-dark text-decoration-none border-bottom">
                <span class="fs-5 fw-semibold">Desafio - Fluxo De Caixa</span>
            </a>
            <ul class="list-unstyled ps-0">
                <li class="mb-1">
                    <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#account-collapse" aria-expanded="false">
                        Contas
                    </button>
                    <div class="collapse" id="account-collapse">
                        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                            <li><a asp-controller="CRUD" asp-action="SelecionarConta" class="link-dark rounded">Alterar Contas de Transações</a></li>
                            <li><a asp-controller="CRUD" asp-action="SelecionarPessoa" class="link-dark rounded">Alterar Cadastro de Pessoas</a></li>
                        </ul>
                    </div>
                </li>
                <li class="mb-1">
                    <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#dashboard-collapse" aria-expanded="false">
                        Relatórios
                    </button>
                    <div class="collapse" id="dashboard-collapse">
                        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                            <li><a asp-controller="Reports" asp-action="SelecionarContaReport" class="link-dark rounded">Transações</a></li>
                            <li><a asp-controller="Reports" asp-action="Contas" class="link-dark rounded">Contas</a></li>
                            <li><a asp-controller="Reports" asp-action="Pessoas" class="link-dark rounded">Pessoas</a></li>
                        </ul>
                    </div>
                </li>
                <li class="mb-1">
                    <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#orders-collapse" aria-expanded="false">
                        Operações
                    </button>
                    <div class="collapse" id="orders-collapse">
                        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                            <li><a asp-controller="CRUD" asp-action="SelecionarContaDeposito" class="link-dark rounded">Depósito</a></li>
                            <li><a asp-controller="CRUD" asp-action="SelecionarContaSaque" class="link-dark rounded">Saque</a></li>
                        </ul>
                    </div>
                </li>
            </ul>
            <div>
                <div style="margin-top: 50px;">
                    <a style="text-decoration: none;" class="link-dark rounded" asp-route-id="@User.Id" asp-controller="User" asp-action="AlterarPessoa">
                        <div class="d-flex user-logged">
                            <span class="user-logged material-symbols-outlined">
                                person
                            </span>
                            <p>@User.Name</p>
                        </div>
                    </a>
                    @Html.ActionLink("Sair", "Sair", "Home", null, new { @class = "btn btn-danger" })
                </div>
            </div>
        </aside>
        <div class="container mt-3">
            @RenderBody()
        </div>
    </main>

    <footer class="border-top footer text-muted">
        <div class="text-center">
            &copy; 2023 - Desafio Fluxo De Caixa
        </div>
    </footer>

</body>
</html>

DesafioFluxoCaixa/Views/Shared/_LayoutLogCad.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] - DesafioFluxoCaixa</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Custom styles for this template -->
    <link href="~/css/sidebars.css" rel="stylesheet">
    <link href="~/css/site.css" rel="stylesheet" />

    <script src="~/lib/knockout-3.5.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout-validation/2.0.4/knockout.validation.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous" asp-append-version="true"></script>
    <script src="~/js/site.js"></script>
    <script src="https://unpkg.com/imask"></script>

</head>
<body>

    <header>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            <div class="container">
                @RenderBody()
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="text-center">
            &copy; 2023 - Desafio Fluxo De Caixa
        </div>
    </footer>

</body>
</html>

DesafioFluxoCaixa/Views/Shared/_LayoutUser.cshtml
@using System.Text.Json
@using Microsoft.AspNetCore.Http
@using DesafioFluxoCaixa.Models.Pessoas
@inject IHttpContextAccessor HttpContextAccessor

@{
    var User = JsonSerializer.Deserialize<Person>(HttpContextAccessor.HttpContext.Session.GetString("User"));
}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] - DesafioFluxoCaixa</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Custom styles for this template -->
    <link href="~/css/sidebars.css" rel="stylesheet">
    <link href="~/css/site.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />

    <script src="~/lib/knockout-3.5.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout-validation/2.0.4/knockout.validation.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous" asp-append-version="true"></script>
    <script src="~/js/site.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.1/dist/sweetalert2.all.min.js"></script>
    <script src="https://unpkg.com/imask"></script>

</head>
<body>

    <main role="main">
        <aside class="flex-shrink-0 p-3 bg-white">
            <a asp-controller="Home" asp-action="Index" class="d-flex align-items-start pb-3 mb-3 link-dark text-decoration-none border-bottom">
                <span class="fs-5 fw-semibold">Desafio - Fluxo De Caixa</span>
            </a>
            <ul class="list-unstyled ps-0">
                <li class="mb-1">
                    <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#account-collapse" aria-expanded="false">
                        Contas
                    </button>
                    <div class="collapse" id="account-collapse">
                        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                            <li><a asp-controller="User" asp-action="AlterarConta" class="link-dark rounded">Alterar Contas de Transações</a></li>
                            <li><a asp-controller="User" asp-action="AlterarPessoa" class="link-dark rounded">Alterar Cadastro de Pessoas</a></li>
                        </ul>
                    </div>
                </li>
                <li class="mb-1">
                    <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#dashboard-collapse" aria-expanded="false">
                        Relatórios
                    </button>
                    <div class="collapse" id="dashboard-collapse">
                        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                            <li><a asp-controller="User" asp-action="TransacoesPorId" class="link-dark rounded">Transações</a></li>
                        </ul>
                    </div>
                </li>
                <li class="mb-1">
                    <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#orders-collapse" aria-expanded="false">
                        Operações
                    </button>
                    <div class="collapse" id="orders-collapse">
                        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                            <li><a asp-controller="User" asp-action="MandarContaDeposito" class="link-dark rounded">Depósito</a></li>
                            <li><a asp-controller="User" asp-action="MandarContaSaque" class="link-dark rounded">Saque</a></li>
                        </ul>
                    </div>
                </li>
            </ul>
            <div>
                <div style="margin-top: 50px;">
                    <a style="text-decoration: none;" class="link-dark rounded" asp-route-id="@User.Id" asp-controller="User" asp-action="AlterarPessoa">
                        <div class="d-flex user-logged">
                            <span class="user-logged material-symbols-outlined">
                                person
                            </span>
                            <p>@User.Name</p>
                        </div>
                    </a>
                    @Html.ActionLink("Sair", "Sair", "Home", null, new { @class = "btn btn-danger" })
                </div>
            </div>
        </aside>
        <div class="container mt-3">
            @RenderBody()
        </div>
    </main>

    <footer class="border-top footer text-muted">
        <div class="text-center">
            &copy; 2023 - Desafio Fluxo De Caixa
        </div>
    </footer>

</body>
</html>